### PR TITLE
v1.0

### LINKED ISSUE #8: Support for PHP 8
PHP 8 support will need to bear in mind changes to the reflection class API. Since this will likely change the structure of the factory class anyway, I would like to take this opportunity to try simplifying the code used to generate the data transfer objects.

### PR DESCRIPTION
**Pull request by aidan-casey**
Adds support for smart generation of properties. Faker will guess the type of data to be populated based on the property name (e.g. homeAddress property is populated with an address).

This would also make the factory API more fluent, add an entry point to the factories through the `Anteris\DataTransferObjectFactory\Factory` class, and make extensions to the generator easier through the `PropertyFactory::regiserProvider()` static method.

This pull request would close #8, #10, and #11.

### CODE REVIEW

**Comment by aidan-casey** [comment]
@morrislaptop - Do you mind checking this out when you have a moment? Be curious to collect any feedback you might have on it.

**Comment by morrislaptop** [comment]
Yep will do!

**Comment by morrislaptop** [comment]
Looks good! A couple of points:

The new readme caught me a little off guard, might be better to use inline class examples rather than `Anteris\Example\DataTransferObject`, while skimming I just saw DataTransferObject::class and got confused

It might be nice to be able to override properties for one-offs like 

```php
Factory::dto(Person::class)->make([
  'gender' => 'male',
  'pet' => $faker->animalName;
]);
```

If it was a common property name, Id' do this with the `PropertyFactory::registerProvider`, but for one-offs I'd appreciate the above.

This would need to be used in collections as well, could borrow from Laravel - https://laravel.com/docs/8.x/database-testing#sequences

**Comment by aidan-casey** [comment]
@morrislaptop - Thanks for that awesome feedback! I made a few adjustments based on your suggestions. Does that look to be what you're after?

1. You can now pass properties to the `state()` or `make()` methods to be manually set.
2. You can now pass `new Sequence()` or `Sequence::make()` to the state method. Alternatively, use the `sequence()` method to handle this for you.

These apply to collection and DTO factories.

**Comment by morrislaptop** [comment]
Works a treat!

**Comment by aidan-casey** [comment]
@morrislaptop - Awesome! Thanks again for the feedback. I am going to get some tests and further documentation assembled then ship this version.

**Comment by aidan-casey** [comment]
@morrislaptop - Unfortunately, this has been a long time in coming, but I think I finally got this nailed. The latest commit supports POPOs (public properties and getter / setter), Spatie DTOs, and custom adapters. It's about 10x faster when it comes to actual generation and fully tested. Do you mind reviewing and seeing if that meets your needs?

**Comment by morrislaptop** [comment]
@aidan-casey ah nice, didn't even know you were working on it! 

One use case that could be useful is a `ConstructorAdapter` which would be useful for those immutable type objects. Something like:

```php
class ImmutabalePropertyData
{
    public function __construct(
        private string $name,
        private array $types,
        private $value = null
    ) {
    }
}
```

**Comment by aidan-casey** [comment]
@morrislaptop Yeah I had started on it a while back but got derailed with a few projects unfortunately.

I can definitely see the use case you mention here. The trick here is that a constructor adapter probably has greater chance of conflicting with one of the others. I took a stab it though, is that what you are looking for?

**Pull request merged**
